/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_finone_JavaCallback */


#ifndef _Included_com_finone_JavaCallback
#define _Included_com_finone_JavaCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_finone_JavaCallback
 * Method:    initCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_finone_JavaCallback_initCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
