/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_finone_JavaInvoke */

#ifndef _Included_com_finone_JavaInvoke
#define _Included_com_finone_JavaInvoke
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_finone_JavaInvoke
 * Method:    invokeMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_finone_JavaInvoke_invokeMethod1
  (JNIEnv *, jobject);

/*
 * Class:     com_finone_JavaInvoke
 * Method:    invokeMethod2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_finone_JavaInvoke_invokeMethod2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_finone_JavaInvoke
 * Method:    invokeMethod3
 * Signature: (Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_finone_JavaInvoke_invokeMethod3
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
